package com.finance.platform.finance.application.dto;

import com.finance.platform.finance.domain.model.AiExtractionMetadata;
import com.finance.platform.finance.domain.model.Receipt;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public record DocumentResponse(
		UUID id,
		UUID firmId,
		UUID clientId,
		String clientName,
		UUID uploadedByUserId,
		String uploadedByName,
		String description,
		String fileName,
		String mimeType,
		Long fileSizeBytes,
		String checksumSha256,
		Receipt.DocumentType documentType,
		Receipt.ReceiptStatus status,
		AiExtractionMetadata.ExtractionStatus extractionStatus,
		BigDecimal confidenceScore,
		String confidenceLabel,
		String suggestedType,
		String suggestedVendorOrCustomer,
		LocalDate suggestedDate,
		BigDecimal suggestedAmount,
		BigDecimal suggestedSubtotal,
		BigDecimal suggestedTaxAmount,
		String suggestedCurrency,
		String suggestedInvoiceNo,
		LocalDate suggestedDueDate,
		String suggestedPaymentMethod,
		String suggestedDescription,
		UUID suggestedCategoryId,
		String suggestedCategoryName,
		String suggestedCategoryCode,
		String ocrText,
		boolean possibleDuplicate,
		UUID existingDocumentId,
		List<UUID> linkedExpenseIds,
		List<UUID> linkedIncomeIds,
		UUID reviewedByUserId,
		Instant reviewedAt,
		String reviewNote,
		String reviewOutcome,
		String failureCode,
		String failureMessage,
		Boolean amountInconsistency,
		String dateWarning,
		BigDecimal supplierConfidence,
		BigDecimal dateConfidence,
		BigDecimal amountConfidence,
		BigDecimal taxConfidence,
		String aiProvider,
		String modelVersion,
		Instant uploadedAt,
		Instant createdAt
) {
}
