package com.finance.platform.core.audit;

public enum AuditAction {
	EXPENSE_CREATED,
	EXPENSE_UPDATED,
	EXPENSE_DELETED,
	EXPENSE_APPROVED,
	INCOME_CREATED,
	INCOME_UPDATED,
	INCOME_DELETED,
	INCOME_APPROVED,
	USER_CREATED,
	FIRM_REGISTERED,
	LOGIN_SUCCESS,
	LOGIN_FAILURE
}
